### ISSUE TITLE
Change Rs to ₹ 

### ISSUE THREAD

**Issue by SingingApple** [iampavangandhi/HackRCDU#12]
### According to the latest conventions, ₹ symbol is used to represent INR. 
![HackRCDU_-_2020-10-17_01 37 31](https://user-images.githubusercontent.com/39864404/96304224-5a4aa400-1019-11eb-8776-e81d0d61e1da.png)

**Comment by iampavangandhi** [comment]
@SingingApple Pointing these small issues are not considered
