### ISSUE TITLE
Youtube logo has incorrect link

### ISSUE THREAD

**Issue by ameybh** [iampavangandhi/HackRCDU#18]
https://github.com/iampavangandhi/HackRCDU/blob/532ec1971ea72334c416bd05148ed121c336096e/index.html#L131-L133

I'd like to make a PR. Please assign it to me and comment the youtube url.

**Comment by iampavangandhi** [comment]
Hey @ameybhavsar24, here is the URL: https://www.youtube.com/channel/UCEJ3JccswK-90yLWip1Nf_w
